"""Configure, record, and package reproducible model-training runs."""

from cycle_forecast.training.daily_refresh import (
    DailyModelRefreshResult,
    DailyModelRefreshStatus,
    refresh_daily_model_if_needed,
)
from cycle_forecast.training.delivery import (
    MODEL_PACKAGE_SCHEMA_VERSION,
    TRAINING_CONFIG_SCHEMA_VERSION,
    ModelPackage,
    TrainingConfig,
    TrainingRun,
    fit_selected_model_package,
    load_model_package,
    load_training_config,
    predict_with_model_package,
    record_training_run,
    save_model_package,
    save_training_run,
)
from cycle_forecast.training.wearable_workflow import (
    WEARABLE_EVALUATION_WORKFLOW_VERSION,
    WearableAggregateEntry,
    WearableCalibrationDiagnostic,
    WearableCandidateDiagnostics,
    WearableCycleDayDiagnostic,
    WearableCycleFoldResult,
    WearableDataDiagnostics,
    WearableEvaluationDiagnostics,
    WearableEvaluationError,
    WearableEvaluationMode,
    WearableEvaluationResult,
    WearableWalkForwardComparison,
    evaluate_local_wearable_models,
)
from cycle_forecast.training.workflow import (
    DEFAULT_MODEL_FILENAME,
    DEFAULT_RUN_FILENAME,
    LocalTrainingResult,
    train_from_local_history,
)

__all__ = [
    "DEFAULT_MODEL_FILENAME",
    "DEFAULT_RUN_FILENAME",
    "MODEL_PACKAGE_SCHEMA_VERSION",
    "TRAINING_CONFIG_SCHEMA_VERSION",
    "WEARABLE_EVALUATION_WORKFLOW_VERSION",
    "DailyModelRefreshResult",
    "DailyModelRefreshStatus",
    "LocalTrainingResult",
    "ModelPackage",
    "TrainingConfig",
    "TrainingRun",
    "WearableAggregateEntry",
    "WearableCalibrationDiagnostic",
    "WearableCandidateDiagnostics",
    "WearableCycleDayDiagnostic",
    "WearableCycleFoldResult",
    "WearableDataDiagnostics",
    "WearableEvaluationDiagnostics",
    "WearableEvaluationError",
    "WearableEvaluationMode",
    "WearableEvaluationResult",
    "WearableWalkForwardComparison",
    "evaluate_local_wearable_models",
    "fit_selected_model_package",
    "load_model_package",
    "load_training_config",
    "predict_with_model_package",
    "record_training_run",
    "refresh_daily_model_if_needed",
    "save_model_package",
    "save_training_run",
    "train_from_local_history",
]
